name: "DefaultItemChanger"
author: TheTealViper
version: "1.14.4.a.1"
api-version: 1.13
description: "Custom drops"
main: me.TheTealViper.defaultitemchanger.DefaultItemChanger
commands:
  defaultitemchanger:
    description: "Main command"
    aliases: [dic]